### PR TITLE
First round of preprocessing

### PR DESCRIPTION
**Pull request by pixochi**

### CODE REVIEW

**Comment by marcinzelent** [comment]
```
DtypeWarning: Columns (28,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  import pandas as pd
Traceback (most recent call last):

  File "<ipython-input-1-fc7e095f61e7>", line 1, in <module>
    runfile('/home/marcin/Documents/school/kea/work/data-science/airbnb-price-prediction/index.py', wdir='/home/marcin/Documents/school/kea/work/data-science/airbnb-price-prediction')

  File "/home/marcin/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "/home/marcin/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/marcin/Documents/school/kea/work/data-science/airbnb-price-prediction/index.py", line 84, in <module>
    'days_since_host_registration': today - dataset['host_since'],

  File "/home/marcin/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py", line 1049, in wrapper
    result = dispatch_to_index_op(op, left, right, pd.DatetimeIndex)

  File "/home/marcin/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py", line 1101, in dispatch_to_index_op
    result = op(left_idx, right)

  File "/home/marcin/anaconda3/lib/python3.7/site-packages/pandas/core/ops.py", line 117, in rsub
    return right - left

  File "/home/marcin/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/datetimelike.py", line 951, in __rsub__
    return -(self - other)

TypeError: unsupported operand type(s) for -: 'DatetimeIndex' and 'datetime.date'
```

**Comment by marcinzelent** [comment]
The error regarding mixed types is gone but I'm still getting the second one:
`TypeError: unsupported operand type(s) for -: 'DatetimeIndex' and 'datetime.date'`

What Python version are you using?

**Comment by pixochi** [comment]
> What Python version are you using?
@marcinzelent 3.7.3

**Review by pekopa — COMMENTED** [review]
Skraaaaa

**Review by pekopa — APPROVED** [review]
Prapapa

**Review by marcinzelent — COMMENTED** [review]
gj

**Pull request merged**
